//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Batch
    {
        public Batch()
        {
            this.Serialnumbers = new HashSet<Serialnumber>();
        }
    
        public int Id { get; set; }
        public int CustomerId { get; set; }
        public System.DateTime Issued { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual ICollection<Serialnumber> Serialnumbers { get; set; }
    }
}
