//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Serialnumber
    {
        public int Id { get; set; }
        public int Year { get; set; }
        public string Serialnumber1 { get; set; }
        public string HardwareVersion { get; set; }
        public string FirmwareVersion { get; set; }
        public int BatchId { get; set; }
    
        public virtual Batch Batch { get; set; }
    }
}
